//! Build script: compile the Sail C++ model class + the C Sail runtime + shim.
//!
//! Default is fully self-contained — vendored pre-generated model + patched
//! runtime with bundled mini-gmp, no Sail/GMP/zlib. Env overrides for building
//! against a freshly generated model (see README Step 2):
//!   SAIL_MODEL_C   path to the generated model .cpp
//!   SAIL_MODEL_INC extra include dir (default: dir of SAIL_MODEL_C)
//!   SAIL_LIB_DIR   external (opam) Sail runtime dir; implies system GMP + zlib
//!   SAIL_SYSTEM_GMP=1  link real libgmp instead of bundled mini-gmp
//!   GMP_LIB_DIR / ZLIB_LIB_DIR / GMP_LIB_NAME / ZLIB_LIB_NAME  link tweaks

use std::env;
use std::path::{Path, PathBuf};

fn unpack_vendored_model(vendor: &Path) -> PathBuf {
    let gz = vendor.join("model.cpp.gz");
    assert!(
        gz.is_file(),
        "vendor/model.cpp.gz is missing and SAIL_MODEL_C is not set. \
         Either restore the vendored model or generate one (README Step 2)."
    );
    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("model.cpp");

    let stale = match (out.metadata(), gz.metadata()) {
        (Ok(o), Ok(g)) => match (o.modified(), g.modified()) {
            (Ok(o), Ok(g)) => o < g,
            _ => true,
        },
        _ => true,
    };
    if stale {
        let mut reader =
            flate2::read::GzDecoder::new(std::fs::File::open(&gz).expect("open model.cpp.gz"));
        let mut writer = std::io::BufWriter::new(
            std::fs::File::create(&out).expect("create OUT_DIR/model.cpp"),
        );
        std::io::copy(&mut reader, &mut writer).expect("decompress model.cpp.gz");
    }
    out
}

fn main() {
    for key in ["SAIL_MODEL_C", "SAIL_LIB_DIR", "SAIL_MODEL_INC", "SAIL_SYSTEM_GMP"] {
        println!("cargo:rerun-if-env-changed={key}");
    }

    let vendor = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("vendor");

    let (model_src, model_inc) = match env::var("SAIL_MODEL_C") {
        Ok(p) => {
            let src = PathBuf::from(p);
            assert!(src.is_file(), "SAIL_MODEL_C does not exist: {src:?}");
            let inc = env::var("SAIL_MODEL_INC")
                .map(PathBuf::from)
                .unwrap_or_else(|_| src.parent().unwrap().to_path_buf());
            (src, inc)
        }
        Err(_) => (unpack_vendored_model(&vendor), vendor.clone()),
    };

    // Runtime selection: default = vendored patched runtime (self-contained,
    // bundled mini-gmp, no elf.c/zlib); SAIL_LIB_DIR = external runtime (system
    // GMP + zlib); SAIL_SYSTEM_GMP = vendored sources but real libgmp.
    let system_runtime = env::var_os("SAIL_LIB_DIR").is_some();
    let system_gmp = system_runtime || env::var_os("SAIL_SYSTEM_GMP").is_some();
    let sail_lib = env::var("SAIL_LIB_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| vendor.join("sail-runtime"));
    assert!(sail_lib.is_dir(), "Sail runtime dir does not exist: {sail_lib:?}");

    let warning_flags = |b: &mut cc::Build| {
        // Sail-generated code is not warning-clean; keep logs readable.
        b.flag_if_supported("-Wno-unused")
            .flag_if_supported("-Wno-unused-parameter")
            .flag_if_supported("-Wno-unused-but-set-variable")
            .flag_if_supported("-Wno-sign-compare")
            .flag_if_supported("-Wno-extra");
    };

    // ---- 1) C++: generated model class + shim ------------------------------
    // Must be compiled FIRST: the model archive references runtime symbols, so
    // it must precede libsailruntime on traditional linkers.
    // C++20 required: generated code uses designated initializers + the `not`
    // token; MSVC needs /std:c++20 (implies /permissive-) for those.
    let mut cxx = cc::Build::new();
    cxx.cpp(true)
        .std("c++20")
        .include(&sail_lib)
        .include(&model_inc)
        .include("csrc")
        // MSVC: model object exceeds the default COFF section limit.
        .flag_if_supported("/bigobj")
        .file(&model_src)
        .file("csrc/shim.cpp");
    // Methods the --cpp backend declares but never emits (generated by
    // scripts/fix_cpp_model.py; ships in vendor/ for the pre-generated model).
    let missing = model_inc.join("model_missing.cpp");
    if missing.is_file() {
        cxx.file(missing);
    }
    warning_flags(&mut cxx);
    if system_gmp {
        cxx.define("SAIL_SYSTEM_GMP", None); // sail.h: include <gmp.h>
    }
    cxx.compile("sailarm");

    // ---- 2) C: Sail runtime -------------------------------------------------
    let mut crt = cc::Build::new();
    crt.include(&sail_lib)
        .flag_if_supported("/std:c11") // timespec_get etc. under MSVC
        .file(sail_lib.join("sail.c"))
        .file(sail_lib.join("rts.c"));
    warning_flags(&mut crt);
    // Sail >= 0.18 split the runtime: sail_assert (sail_failure.c) and
    // sail_config.c (needs cJSON.c) are referenced by the generated code.
    for extra in ["sail_failure.c", "sail_config.c", "cJSON.c"] {
        let p = sail_lib.join(extra);
        if p.is_file() {
            crt.file(p);
        }
    }
    if system_gmp {
        crt.define("SAIL_SYSTEM_GMP", None);
    } else {
        crt.file(vendor.join("sail-runtime/mini-gmp.c"))
            .file(vendor.join("sail-runtime/mini-mpq.c"));
    }
    if system_runtime {
        // Only external runtimes compile elf.c; the model references nothing in it.
        crt.file(sail_lib.join("elf.c"));
    }
    crt.compile("sailruntime");

    // ---- native link deps ----------------------------------------------------
    let target_env = env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();

    if let Ok(dir) = env::var("GMP_LIB_DIR") {
        println!("cargo:rustc-link-search=native={dir}");
    }
    if let Ok(dir) = env::var("ZLIB_LIB_DIR") {
        println!("cargo:rustc-link-search=native={dir}");
    }
    if system_gmp {
        let gmp = env::var("GMP_LIB_NAME").unwrap_or_else(|_| "gmp".into());
        println!("cargo:rustc-link-lib={gmp}");
    }
    if system_runtime {
        let zlib = env::var("ZLIB_LIB_NAME")
            .unwrap_or_else(|_| if target_env == "msvc" { "zlib".into() } else { "z".into() });
        println!("cargo:rustc-link-lib={zlib}"); // external elf.c may use zlib
    }

    for p in [
        model_src.as_path(),
        Path::new("vendor/model.cpp.gz"),
        Path::new("vendor/sail-runtime"),
        Path::new("csrc/shim.cpp"),
        Path::new("build.rs"),
    ] {
        println!("cargo:rerun-if-changed={}", p.display());
    }
}
